import Head from 'next/head'
import { useEffect, useState } from 'react'
import NavBar from './frameComponents/NavBar'
import Quickswap from './defiApps/Quickswap'
import Uniswap from './defiApps/Uniswap'
import Curve from './defiApps/Curve'
import Aave from './defiApps/Aave'


export default function Home() {

  const [hub, setHub] = useState(1);

  const changeView = (view) => {
    setHub(view)
  }

  

  //const themePack = [`bg-purple-500`,`bg-purple-800`,`border-purple-500`,`border-purple-800`]

  // const lightBG = `bg-purple-500`
  // const darkBG = `bg-purple-800`
  // const lightBorder = `border-purple-500`
  // const darkBorder = `border-purple-800`

  const allColors = {
    red: [`bg-red-500`,`bg-red-800`,`border-red-500`,`border-red-800`],
    blue: [`bg-blue-500`,`bg-blue-800`,`border-blue-500`,`border-blue-800`],
    purple: [`bg-purple-500`,`bg-purple-800`,`border-purple-500`,`border-purple-800`]
  }

  const [theme, setTheme] = useState(allColors.purple)

  const lightBG = theme[0]
  const darkBG = theme[1]
  const lightBorder = theme[2]
  const darkBorder = theme[3]

  const changeTheme = (themeColor) => {
    setTheme(themeColor)
  }


  
  return (
    
    <div className={`flex flex-row-reverse h-screen w-screen ${lightBG}`}>

      <Head>
        <title>DefiHub V1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`flex flex-grow p-2 w-fit flex-row-reverse ${darkBorder}`}>
        {hub === 1 && <Quickswap /> } 
        {hub === 2 && <Uniswap /> }
        {hub === 3 && <Curve /> } 
        {hub === 4 && <Aave /> }
      </div>
      
      <div className={`h-screen w-20 p-2 z-10 ${darkBG}`}>
        <NavBar function={changeView} color={lightBG}/>
      </div>
      

    </div>
  )
}
